name: subiquity_test
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build_runner: ^2.2.0
  mockito: 5.4.2
  path: ^1.8.3
  subiquity_client: ^0.1.0

dev_dependencies:
  ubuntu_lints:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_lints
      ref: main
  test: any
