name: sysmetrics
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  meta: ^1.9.1

dev_dependencies:
  ffigen: ^9.0.1
  ubuntu_lints:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_lints
      ref: main
